name: filter_ips

on:
  push:
    paths:
      - 'filter_ips.py'
      - '.github/workflows/filter_ips.yml'
      - 'duplicate-remove.txt'
      - 'sources_cidr_seed.txt'
      - 'domain.txt'
      - 'candidates.txt'
      - 'GeoLite2-Country.mmdb'
  workflow_dispatch:

jobs:
  filter_job:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v4

      - name: 2. 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. 安装依赖
        run: |
          pip install requests geoip2

      - name: 下载 GeoIP 数据库
        run: |
          wget -q https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-Country.mmdb

      - name: 4. 运行清理与抽样
        run: |
          python3 filter_ips.py

      - name: 5. 提交结果
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 将 targets.txt 和历史数据库 targets_history.db 都加入暂存区
          git add targets.txt targets_history.db targets_history.txt

          # 检查是否有实质性改动（ targets.txt 或数据库是否有更新）
          if git diff --cached --quiet; then
            echo "没有发现新数据，无需更新。"
          else
            git commit -m "Auto: 更新IP过滤结果及历史数据库 $(date +'%Y-%m-%d %H:%M:%S') [skip ci]"
            git push origin main
          fi
